version: '3.8'

services:
  worker:
    build: .
    container_name: celery-worker
    environment:
      - REDIS_URL=redis://host.docker.internal:6379/0
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
      - CELERY_RESULT_BACKEND=redis://host.docker.internal:6379/0
    command: celery -A celery_app worker --loglevel=info --queues=general_queue,ai_queue,data_queue --concurrency=4
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - celery-network

  flower:
    build: .
    container_name: celery-flower
    environment:
      - REDIS_URL=redis://host.docker.internal:6379/0
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
      - CELERY_RESULT_BACKEND=redis://host.docker.internal:6379/0
    command: celery -A celery_app flower --port=5555 --basic_auth=admin:password123
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - celery-network

  beat:
    build: .
    container_name: celery-beat
    environment:
      - REDIS_URL=redis://host.docker.internal:6379/0
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
      - CELERY_RESULT_BACKEND=redis://host.docker.internal:6379/0
    command: celery -A celery_app beat --loglevel=info
    volumes:
      - .:/app
      - ./celerybeat-schedule:/app/celerybeat-schedule
    restart: unless-stopped
    networks:
      - celery-network

networks:
  celery-network:
    driver: bridge
