apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: bae-recipe
  labels:
    app: celery-worker
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
        component: worker
    spec:
      containers:
      - name: celery-worker
        image: ghcr.io/teamshackathon/prod/aws-genai-worker:latest
        imagePullPolicy: Always
        command: ["celery", "-A", "celery_app", "worker", "--loglevel=info", "--queues=recipe_gen_queue", "--concurrency=4"]
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: REDIS_URL
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: CELERY_RESULT_BACKEND
        - name: WEBSOCKET_URL
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: WEBSOCKET_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
# Celery Beat Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: bae-recipe
  labels:
    app: celery-beat
    component: scheduler
spec:
  replicas: 1  # Beat should only have one replica to avoid duplicate scheduling
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
        component: scheduler
    spec:
      containers:
      - name: celery-beat
        image: ghcr.io/teamshackathon/prod/aws-genai-worker:latest
        imagePullPolicy: Always
        command: ["celery", "-A", "celery_app", "beat", "--loglevel=info"]
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: REDIS_URL
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: CELERY_RESULT_BACKEND
        - name: WEBSOCKET_URL
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: WEBSOCKET_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: beat-schedule
          mountPath: /app/data
      volumes:
      - name: beat-schedule
        emptyDir: {}
---
# Flower (Monitoring) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flower
  namespace: bae-recipe
  labels:
    app: celery-flower
    component: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-flower
  template:
    metadata:
      labels:
        app: celery-flower
        component: monitor
    spec:
      containers:
      - name: celery-flower
        image: ghcr.io/teamshackathon/prod/aws-genai-worker:latest
        imagePullPolicy: Always
        command: ["celery", "-A", "celery_app", "flower", "--port=5555"]
        args:
        - --basic_auth=$(FLOWER_USERNAME):$(FLOWER_PASSWORD)
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: REDIS_URL
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: CELERY_RESULT_BACKEND
        - name: FLOWER_USERNAME
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: FLOWER_BASIC_AUTH_USERNAME
        - name: FLOWER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: celery-secrets
              key: FLOWER_BASIC_AUTH_PASSWORD
        ports:
        - containerPort: 5555
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"