apiVersion: v1
kind: Service
metadata:
  name: flower-service-nodeport
  namespace: bae-recipe
  labels:
    app: flower-service
spec:
  ports:
  - port: 5555
    targetPort: 5555
    name: http
    nodePort: 30234
  type: NodePort
  selector:
    app: celery-flower
