apiVersion: v1
kind: Service
metadata:
  name: celery-flower-service
  namespace: bae-recipe
spec:
  selector:
    app:  celery-flower
  ports:
  - port: 5555
    targetPort: 5555
    protocol: TCP
    name: http
  type: ClusterIP